routes/web.php
<?php

use App\Http\Controllers\Backend\AuthController;
use App\Http\Controllers\Backend\BookingController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\TicketController;
use App\Http\Controllers\Backend\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app.frontend.index');
});

Route::get('login', [AuthController::class, 'loginForm'])->name('login-form');
Route::get('register', [AuthController::class, 'registerForm'])->name('register-form');
Route::post('register', [AuthController::class, 'register'])->name('register');
Route::post('login', [AuthController::class, 'login'])->name('login');

Route::prefix('application')->middleware('auth')->group(function() {
    Route::get('register-google2fa', [AuthController::class, 'registerGoogle2Fa'])->name('register-google2fa');
    Route::get('complete-registration', [AuthController::class, 'completeRegistration'])->name('complete-registration');

    // Route::middleware('2fa  ')->group(function() {
        Route::get('logout', [AuthController::class, 'logout'])->name('logout');
        Route::post('/2fa', function () {
            return redirect()->route('booking.index');
        })->name('2fa');
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
        
        Route::prefix('user')->name('user.')->group(function() {
            Route::get('/', [UserController::class, 'index'])->name('index');
            Route::get('create', [UserController::class, 'create'])->name('create');
            Route::post('store', [UserController::class, 'store'])->name('store');
            Route::get('show/{id}', [UserController::class, 'show'])->name('show');
            Route::post('update/{id}', [UserController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [UserController::class, 'delete'])->name('delete');
        });

        Route::prefix('booking')->name('booking.')->group(function() {
            Route::get('/', [BookingController::class, 'index'])->name('index');
            Route::get('create', [BookingController::class, 'create'])->name('create');
            Route::post('store', [BookingController::class, 'store'])->name('store');
            Route::get('show/{id}', [BookingController::class, 'show'])->name('show');
            // Route::post('update/{id}', [BookingController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [BookingController::class, 'delete'])->name('delete');
            Route::post('upload/proof-of-payment', [BookingController::class, 'uploadProofOfPayment'])->name('upload-proof-of-payment');
            Route::post('approve-payment', [BookingController::class, 'approvePayment'])->name('approve-payment');
        });

        Route::prefix('ticket')->name('ticket.')->group(function() {
            Route::get('/', [TicketController::class, 'index'])->name('index');
            Route::get('create', [TicketController::class, 'create'])->name('create');
            Route::post('store', [TicketController::class, 'store'])->name('store');
            Route::get('show/{id}', [TicketController::class, 'show'])->name('show');
            Route::post('update/{id}', [TicketController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [TicketController::class, 'delete'])->name('delete');
        });

        Route::get('qr-scanner', function() {
            return view('app.backend.qr-code.qr-scanner', ['activePage' => 'QR Scanner']);
        })->name('qr-scanner');
    // });
});

Route::get('checking-qr', [BookingController::class, 'checkingQr']);

resources/views/app/backend/layout/partials/header.blade.php
<aside class="sidenav bg-white navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-4 " id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-secondary opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" href="#">
        <img src="{{ asset('assets/backend/img/logo-ct-dark.png') }}" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold">{{ auth()->user()->name }}</span>
      </a>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        @if(auth()->user()->user_level == 'Admin')
          <li class="nav-item">
            <a class="nav-link {{ $activePage == 'Dashboard' ? 'active' : '' }}" href="{{ route('dashboard') }}">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="ni ni-tv-2 text-primary text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ $activePage == 'Ticket' ? 'active' : '' }}" href="{{ route('ticket.index') }}">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Tickets</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ $activePage == 'Booking' ? 'active' : '' }}" href="{{ route('booking.index') }}">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Bookings</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ $activePage == 'Users' ? 'active' : '' }}" href="{{ route('user.index') }}">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Users</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ $activePage == 'QR Scanner' ? 'active' : '' }}" href="{{ route('qr-scanner') }}">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">QR Scanner</span>
            </a>
          </li>
        @else
          <li class="nav-item">
            <a class="nav-link {{ $activePage == 'Booking' ? 'active' : '' }}" href="{{ route('booking.index') }}">
              <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
                <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
              </div>
              <span class="nav-link-text ms-1">Bookings</span>
            </a>
          </li>
        @endif
      </ul>
    </div>
    <hr class="horizontal dark mt-0">
    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ route('logout') }}">
            <div class="icon icon-shape icon-sm border-radius-md text-center me-2 d-flex align-items-center justify-content-center">
              <i class="ni ni-calendar-grid-58 text-warning text-sm opacity-10"></i>
            </div>
            <span class="nav-link-text ms-1">Logout</span>
          </a>
        </li>
      </ul>
    </div>
</aside>

resources/views/app/backend/layout/partials/navbar.blade.php
 <!-- Navbar -->
 <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl " id="navbarBlur" data-scroll="false">
    <div class="container-fluid py-1 px-3">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
          <li class="breadcrumb-item text-sm"><a class="opacity-5 text-white" href="javascript:;">Pages</a></li>
          <li class="breadcrumb-item text-sm text-white active" aria-current="page">{{ $activePage }}</li>
        </ol>
        <h6 class="font-weight-bolder text-white mb-0">{{ $activePage }}</h6>
      </nav>
    </div>
  </nav>
  <!-- End Navbar -->

resources/views/app/backend/layout/partials/scripts.blade.php
<!--   Core JS Files   -->
<script src="{{ asset('assets/backend/js/core/popper.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/core/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/plugins/perfect-scrollbar.min.js') }}"></script>
<script src="{{ asset('assets/backend/js/plugins/smooth-scrollbar.min.js') }}"></script>
<script>
var win = navigator.platform.indexOf('Win') > -1;
if (win && document.querySelector('#sidenav-scrollbar')) {
    var options = {
    damping: '0.5'
    }
    Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
}
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{{ asset('assets/backend/js/argon-dashboard.min.js?v=2.0.4') }}"></script>
<script src="{{ asset('assets/backend/js/plugins/smooth-scrollbar.min.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>

@yield('scripts')

resources/views/app/backend/layout/partials/styles.blade.php
<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
<!-- Nucleo Icons -->
<link href="{{ asset('assets/backend/css/nucleo-icons.css') }}" rel="stylesheet" />
<link href="{{ asset('assets/backend/css/nucleo-svg.css') }}" rel="stylesheet" />
<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<link href="{{ asset('assets/backend/css/nucleo-svg.css') }}" rel="stylesheet" />
<!-- CSS Files -->
<link id="pagestyle" href="{{ asset('assets/backend/css/argon-dashboard.css?v=2.0.4') }}" rel="stylesheet" />