routes/web.php
<?php

use App\Http\Controllers\Backend\AuthController;
use App\Http\Controllers\Backend\BookingController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\TicketController;
use App\Http\Controllers\Backend\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app.frontend.index');
});

Route::get('login', [AuthController::class, 'loginForm'])->name('login-form');
Route::get('register', [AuthController::class, 'registerForm'])->name('register-form');
Route::post('register', [AuthController::class, 'register'])->name('register');
Route::post('login', [AuthController::class, 'login'])->name('login');

Route::prefix('application')->middleware('auth')->group(function() {
    Route::get('register-google2fa', [AuthController::class, 'registerGoogle2Fa'])->name('register-google2fa');
    Route::get('complete-registration', [AuthController::class, 'completeRegistration'])->name('complete-registration');

    // Route::middleware('2fa  ')->group(function() {
        Route::get('logout', [AuthController::class, 'logout'])->name('logout');
        Route::post('/2fa', function () {
            return redirect()->route('booking.index');
        })->name('2fa');
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
        
        Route::prefix('user')->name('user.')->group(function() {
            Route::get('/', [UserController::class, 'index'])->name('index');
            Route::get('create', [UserController::class, 'create'])->name('create');
            Route::post('store', [UserController::class, 'store'])->name('store');
            Route::get('show/{id}', [UserController::class, 'show'])->name('show');
            Route::post('update/{id}', [UserController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [UserController::class, 'delete'])->name('delete');
        });

        Route::prefix('booking')->name('booking.')->group(function() {
            Route::get('/', [BookingController::class, 'index'])->name('index');
            Route::get('create', [BookingController::class, 'create'])->name('create');
            Route::post('store', [BookingController::class, 'store'])->name('store');
            Route::get('show/{id}', [BookingController::class, 'show'])->name('show');
            // Route::post('update/{id}', [BookingController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [BookingController::class, 'delete'])->name('delete');
            Route::post('upload/proof-of-payment', [BookingController::class, 'uploadProofOfPayment'])->name('upload-proof-of-payment');
            Route::post('approve-payment', [BookingController::class, 'approvePayment'])->name('approve-payment');
        });

        Route::prefix('ticket')->name('ticket.')->group(function() {
            Route::get('/', [TicketController::class, 'index'])->name('index');
            Route::get('create', [TicketController::class, 'create'])->name('create');
            Route::post('store', [TicketController::class, 'store'])->name('store');
            Route::get('show/{id}', [TicketController::class, 'show'])->name('show');
            Route::post('update/{id}', [TicketController::class, 'update'])->name('update');
            Route::delete('delete/{id}', [TicketController::class, 'delete'])->name('delete');
        });

        Route::get('qr-scanner', function() {
            return view('app.backend.qr-code.qr-scanner', ['activePage' => 'QR Scanner']);
        })->name('qr-scanner');
    // });
});

Route::get('checking-qr', [BookingController::class, 'checkingQr']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'email',
        'phone',
        'password',
        'user_level',
        'gender',
        'address',
        'google2fa_secret'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class AuthController extends Controller
{
    public function loginForm()
    {
        if(Auth::check()) {
            if(!Auth::user()->google2fa_secret) {
                return redirect()->route('register-google2fa');
            }
            return redirect()->route('dashboard');
        } else {
            return view('app.backend.auth.login');
        }
    }

    public function registerForm()
    {
        return view('app.backend.auth.register');
    }

    public function login(Request $request)
    {
        $this->validate($request, [
            'username' => 'required', 
            'password' => 'required'
        ]);

        $user = User::where('username', $request->username)->first();
        if(empty($user)) {
            return redirect()->back()->withErrors(['error' => 'User is not found!']);
        }

        if(!Hash::check($request->password, $user->password)) {
            return redirect()->back()->withErrors(['error' => 'Password is not match!']);
        }

        Auth::attempt([
            'username' => $request->username,
            'password' => $request->password
        ]);

        if(empty(auth()->user()->google2fa_secret)) {
            return redirect()->route('register-google2fa');
        } 
        
        if(auth()->user()->user_level == 'Admin') {
            return redirect()->route('dashboard');
        } else {
            return redirect()->route('booking.index');
        }
    }

    public function register(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'username' => 'required',
            'email' => 'required|email',
            'password' => 'required|confirmed',
            'gender' => 'required',
            'address' => 'required'
        ]);

        User::create([
            'name' => $request->name,
            'username' => $request->username,
            'email' => $request->email,
            'phone' => $request->phone,
            'password' => Hash::make($request->password),
            'gender' => $request->gender,
            'address' => $request->address,
            'user_level' => 'User'
        ]);

        Session::flash('message', 'Successfully registred!'); 
        return redirect()->route('login-form');
    }

    public function logout(Request $request)
    {
        Auth::logout();
    
        $request->session()->invalidate();
    
        $request->session()->regenerateToken();
    
        return redirect('/login');
    }

    public function registerGoogle2Fa(Request $request) 
    {
        // Initialise the 2FA class
        $google2fa = app('pragmarx.google2fa');

        // Add the secret key to the registration data
        $google2fa_secret = $google2fa->generateSecretKey();

        // Generate the QR image. This is the image the user will scan with their app
        // to set up two factor authentication
        $QR_Image = $google2fa->getQRCodeInline(
            config('app.name'),
            auth()->user()->email,
            $google2fa_secret
        );

        User::where('id', auth()->user()->id)->update([
            'google2fa_secret' => $google2fa_secret
        ]);

        // Pass the QR barcode image to our view
        return view('app.backend.google2fa.register', [
            'QR_Image' => $QR_Image, 
            'secret' => $google2fa_secret,
            'activePage' => ''
        ]);
    } 

    public function completeRegistration(Request $request)
    {
        return view('app.backend.google2fa.index');
    }
}

app/Http/Controllers/Backend/BookingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Barcode;
use App\Models\Booking;
use App\Models\BookingDetail;
use App\Models\Ticket;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;

class BookingController extends Controller
{
    public function index(Request $request)
    {
        if($request->success_message) {
            Session::flash('success', 'Success created booking'); 
        }

        $bookings = Booking::latest();

        if(auth()->user()->user_level == 'User') {
            $bookings = $bookings->where('user_id', auth()->user()->id);
        }
        
        $bookings = $bookings->get();

        return view('app.backend.booking.index',[
            'activePage' => 'Booking',
            'bookings' => $bookings
        ]);
    }

    public function create() 
    {
        $tickets = Ticket::latest()->get();

        return view('app.backend.booking.create', [
            'activePage' => 'Booking',
            'tickets' => $tickets
        ]);
    }

    public function store(Request $request) 
    {
        if(empty($request->date)) {
            return response()->json([
                'error' => true,
                'message' => 'Please select a date!'
            ], 410);
        }
        
        if(empty($request->ticket_selected)) {
            return response()->json([
                'error' => true,
                'message' => 'Please select the ticket!'
            ], 410);
        }

        $booking = Booking::create([
            'booking_code' => 'BK-'.random_int(0, 999999).Carbon::now()->format('YmdHi'),
            'user_id' => Auth::user()->id,
            'date' => $request->date,
            'status' => 'Ordered',
            'amount' => $request->total_amount
        ]);

        foreach($request->ticket_selected as $ticket) {
            $bookingDetail = BookingDetail::create([
                'booking_id' => $booking->id,
                'ticket_id' => $ticket['id'],
                'qty' => $ticket['qty'],
                'amount' => $ticket['amount']
            ]);
        }

        return response()->json([
            'error' => false,
            'message' => 'Success created booking'
        ]);
    }

    public function show($id) 
    {
        $booking = Booking::find($id);

        $barcode = ! empty($booking->barcode) ? $booking->barcode : null;
        // openssl_public_encrypt($barcode, $encrypted, file_get_contents(resource_path('key/publickey.pem')));

        $encrypt = Crypt::encrypt($barcode);
        $content = 'http://localhost:8000/checking-qr?barcode='.$encrypt;

        $generateQr = "https://image-charts.com/chart?chs=150x150&cht=qr&choe=UTF-8&chl=".$content;

        return view('app.backend.booking.show', [
            'activePage' => 'Booking',
            'booking' => $booking,
            'generateQr' => $generateQr
        ]);
    }

    public function update(Request $request, $id) 
    {
        $this->validate($request, [
            'date' => 'required',
            'amount' => 'required|min:1',
        ]);

        $items = json_decode($request->items);
        if(count($items) == 0) {
            return redirect()->back()->withErrors(['error' => 'Please select the ticket!']);
        }

        $booking = Booking::find($id)->update([
            'booking_code' => 'BK-'.random_int(0, 999999).Carbon::now()->format('YmdHi'),
            'user_id' => Auth::user()->id,
            'date' => $request->date,
            'status' => 'Ordered',
            'amount' => $request->amount
        ]);
        
        BookingDetail::where('booking_id', $id)->delete();

        foreach($items as $item) {
            $bookingDetail = BookingDetail::create([
                'booking_id' => $booking->id,
                'ticket_id' => $item->ticket_id,
                'qty' => $item->qty,
                'amount' => $item->amount
            ]);
        }

        return redirect()->route('booking.index')->with('success', 'Successfully Updated Booking');
    }

    public function delete($id) 
    {
        Booking::find($id)->delete();
        BookingDetail::where('booking_id', $id)->delete();

        return redirect()->back()->with('success', 'Success Deleted Booking');
    }

    public function uploadProofOfPayment(Request $request)
    {
        if($request->file('proof_of_payment')) {
            $imageUrl = $request->file('proof_of_payment')->store('proofOfPayment', ['disk' => 'my_files']);
            Booking::find($request->booking_id)->update([
                'proof_of_payment' => $imageUrl,
                'status' => 'Waiting Approval'
            ]);

            return redirect()->back()->with('success', 'Success Uploaded Proof Of Payment');
        } else {
            return redirect()->back()->withErrors(['error' => 'Error Uploaded Proof Of Payment']);
        }
    }

    public function approvePayment(Request $request) 
    {
        if($request->approved) {
            Booking::find($request->booking_id)->update([
                'status' => 'Approved',
                'barcode' => str_shuffle(Carbon::now()->format('Ymd').random_int(0, 99999999999999999))
            ]);
            return redirect()->back()->with('success', 'Success Approve Payment');
        } else {
            return redirect()->back()->withErrors(['error' => 'Error Approve Payment']);
        }
    }

    public function checkingQr(Request $request)
    {
        $barcode = $request->barcode;
        $barcode = Crypt::decrypt($barcode);

        $booking = Booking::where('barcode', $barcode)->first();
        if(!$booking) {
            return 'Booking not found!';
        }

        if(Carbon::createFromFormat('Y-m-d', $booking->date)->format('Y-m-d') != Carbon::now()->format('Y-m-d')) {
            return 'QR Expired!';
        }

        if($booking->is_used) {
            return 'QR Already used!';
        }

        $booking->update(['is_used' => 1]);

        return view('app.backend.booking.show-by-qr', [
            'activePage' => 'Booking',
            'booking' => $booking
        ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Booking;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(Request $request)
    {
        if($request->q != null) {
            if($request->q == 'Daily') {
                $startDateCarbon = Carbon::now()->startOfDay()->format('Y-m-d H:i:s');
                $endDateCarbon = Carbon::now()->endOfDay()->format('Y-m-d H:i:s');
            } else if ($request->q == 'Weekly') {
                $startDateCarbon = Carbon::now()->subWeek(1)->startOfDay()->format('Y-m-d H:i:s');
                $endDateCarbon = Carbon::now()->endOfDay()->format('Y-m-d H:i:s');
            } else if ($request->q == 'Monthly') {
                $startDateCarbon = Carbon::now()->startOfDay()->subMonth(1)->format('Y-m-d H:i:s');
                $endDateCarbon = Carbon::now()->endOfDay()->format('Y-m-d H:i:s');
            } else if ($request->q == 'Yearly') {
                $startDateCarbon = Carbon::now()->startOfDay()->subYear(1)->format('Y-m-d H:i:s');
                $endDateCarbon = Carbon::now()->endOfDay()->format('Y-m-d H:i:s');
            }

            $totalVisitors = Booking::whereBetween('created_at', [$startDateCarbon, $endDateCarbon])->where('is_used', 1)->count();
            $totalAmount = Booking::whereBetween('created_at', [$startDateCarbon, $endDateCarbon])->where('status', 'Approved')->sum('amount');
            $totalUser = User::whereBetween('created_at', [$startDateCarbon, $endDateCarbon])->count();
            $totalBooking = Booking::whereBetween('created_at', [$startDateCarbon, $endDateCarbon])->count();
        }

        return view('app.backend.dashboard', [
            'activePage' => 'Dashboard',
            'q' => $request->q,
            'totalVisitors' => $totalVisitors ?? 0,
            'totalAmount' => $totalAmount ?? 0,
            'totalUser' => $totalUser ?? 0,
            'totalBooking' => $totalBooking ?? 0
        ]);
    }
}

resources/views/app/backend/user/create.blade.php
@extends('app.backend.layout.app')

@section('contents')
<main class="main-content position-relative border-radius-lg ">
    @include('app.backend.layout.partials.navbar')
   <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<i class="fas fa-plus"></i>
						Create User
					</div>
					<div class="card-body">
						@include('app.backend.auth.layout.partials.alert-message')
						<form method="POST" action="{{route('user.store')}}">
							@csrf
							<div class="form-group">
								<label>Name</label>
								<input type="name" name="name" class="form-control @error('name') is-invalid @enderror">
								@error('name')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Username</label>
								<input type="username" name="username" class="form-control @error('username') is-invalid @enderror">
								@error('username')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Email</label>
								<input type="email" name="email" class="form-control @error('email') is-invalid @enderror">
								@error('email')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Phone Number</label>
								<input type="number" name="phone" class="form-control @error('phone') is-invalid @enderror">
								@error('phone')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Password</label>
								<input type="password" name="password" class="form-control @error('password') is-invalid @enderror">
								@error('password')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Role</label>
								<select class="form-control @error('role') is-invalid @enderror" name="role">
									<option value="">Select Role</option>
									<option value="User">User</option>
									<option value="Admin">Admin</option>
								</select>
								@error('role')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Gender</label>
								<select class="form-control @error('gender') is-invalid @enderror" name="gender">
									<option value="">Select Gender</option>
									<option value="Laki">Male</option>
									<option value="Perempuan">Female</option>
								</select>
								@error('gender')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Address</label>
								<textarea type="text" name="address" rows="5" class="form-control @error('address') is-invalid @enderror" ></textarea> 
								@error('address')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<button class="btn btn-primary" type="submit">Create User</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

@endsection

resources/views/app/backend/user/edit.blade.php
@extends('app.backend.layout.app')

@section('contents')
<main class="main-content position-relative border-radius-lg ">
    @include('app.backend.layout.partials.navbar')
   <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<i class="fas fa-plus"></i>
						Edit {{ $user->name }}
					</div>
					<div class="card-body">
						@include('app.backend.auth.layout.partials.alert-message')
						<form method="POST" action="{{route('user.update', $user->id)}}">
							@csrf
							<div class="form-group">
								<label>Name</label>
								<input type="name" name="name" class="form-control @error('name') is-invalid @enderror" value="{{ $user->name }}">
								@error('name')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Username</label>
								<input type="username" name="username" class="form-control @error('username') is-invalid @enderror" value="{{ $user->username }}">
								@error('username')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Email</label>
								<input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ $user->email }}">
								@error('email')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Phone Number</label>
								<input type="number" name="phone" class="form-control @error('phone') is-invalid @enderror" value="{{ $user->phone }}">
								@error('phone')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Password</label>
								<input type="password" name="password" class="form-control @error('password') is-invalid @enderror" >
								 <small class="form-text text-muted ml-3 mt-2">Leave password blank if you don't want to change the password.</small>
								@error('password')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Role</label>
								<select class="form-control @error('role') is-invalid @enderror" name="role">
									<option value="{{$user->user_level}}">{{$user->user_level}}</option>
									<option value="User">User</option>
									<option value="Admin">Admin</option>
								</select>
								@error('role')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Gender</label>
								<select class="form-control @error('gender') is-invalid @enderror" name="gender">
									<option value="{{$user->gender}}">{{$user->gender}}</option>
									<option value="Laki">Male</option>
									<option value="Perempuan">Female</option>
								</select>
								@error('gender')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<div class="form-group">
								<label>Address</label>
								<textarea type="text" name="address" rows="5" class="form-control @error('address') is-invalid @enderror" >{{$user->address}}</textarea> 
								@error('address')
								 	<div id="validationServerUsernameFeedback" class="invalid-feedback">
								        {{$message}}
								    </div>
								@enderror
							</div>
							<button class="btn btn-primary" type="submit">Update User</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

@endsection

resources/views/app/backend/user/index.blade.php
@extends('app.backend.layout.app')

@section('contents')
<main class="main-content position-relative border-radius-lg ">
    @include('app.backend.layout.partials.navbar')
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
              @if(session('success'))
                  <div class="alert alert-success">
                      {{ session('success') }}
                  </div>
              @endif
              @if(auth()->user()->user_level == 'User')
                <a href="{{ route('user.create') }}" class="btn btn-primary">Create User</a>
              @endif
              <h6>Users table</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center justify-content-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Name</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Email</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Phone</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">User Level</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Gender</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Address</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($users as $user)
                      <tr>
                        <td>
                          <h6 class="mb-0 text-sm" style="margin-left: 10px;">{{ $user->name }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->email }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->phone }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->user_level }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->gender }}</h6>
                        </td>
                        <td>
                          <h6 class="mb-0 text-sm">{{ $user->address }}</h6>
                        </td>
                        <td class="align-middle d-flex flex-wrap">
                          <a style="padding:4px 0;" class="btn btn-link text-secondary mb-0" href="{{ route('user.show', $user->id) }}">
                            <i class="fas fa-eye"></i>
                          </a>
                          @if(auth()->user()->id != $user->id)
                            <form  method="post" action="{{ route('user.delete', $user->id) }}">
                              @csrf
                              @method('DELETE')
                              <button style="padding:0" type="submit" class="btn btn-link text-secondary mb-0 mx-2">
                                <i class="fas fa-trash"></i>
                              </button>
                            </form>
                          @endif
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
@endsection